config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "help" => "static_pages#help"
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  get "suggestion" => "suggestions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :products, only: [:show, :index] do
    resources :comments, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :update, :index]
  resources :order_details, except: [:show, :new]
  resources :comments
  resources :categories, only: [:show, :index]
  resources :users, except: [:destroy]
  namespace :admin do
    resources :users, only: [:destroy, :index]
    resources :categories
    resources :products
    resources :suggestions, only: [:index, :destroy]
    resources :orders, except: [:new, :destroy, :create]
  end
  resources :relationships, only: [:create, :destroy, :index]
  resources :rates, only: [:create]
  resources :suggestions, only: [:new, :create]
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  
  has_many :order_details

  before_create :init_order
  before_save :update_subtotal

  scope :order_by_status, -> (status) {where status: status}

  enum status: ["blank", "ordered", "shipping", "delivered"]

  def subtotal
    order_details.collect {|od| od.valid? ? (od.quantity * od.unit_price) : 0}.sum
  end

  private
  def init_order
    self.status = 0
    self.total_pay = 0
  end

  def update_subtotal
    self[:total_pay] = subtotal
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :find_order, only: [:edit, :update, :show]

  def edit
    @statuses = Order.statuses
  end

  def update
    if @order.update_attributes order_params
      flash[:success] = t "order.update_succ"
      redirect_to admin_orders_path
    else
      render :edit
    end
  end

  def index
    if params[:status]
      @orders = Order.order_by_status(check_status params[:status])
        .paginate page: params[:page], per_page: Settings.size
    else
      @orders = Order.order_by_status(1)
        .paginate page: params[:page], per_page: Settings.size
    end
  end

  def show
    @order_details = @order.order_details
  end

  private
  def order_params
    params.require(:order).permit :status
  end

  def find_order
    @order = Order.find_by id: params[:id]
    if @order.nil?
      flash[:danger] = t "flash.order_nil"
      redirect_to admin_orders_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, :normal_user?
  before_action :find_order, only: [:show, :update]
  before_action :correct_user, only: [:show, :update]

  def show
    @order_details = @order.order_details
      .paginate page: params[:page], per_page: Settings.size
  end

  def index
    @orders = Order.find_by(user_id: current_user.id)
      .paginate page: params[:page], per_page: Settings.size
  end

  def update
    if @order.update_attributes order_params
      flash[:success] = t "order.ordered"
      redirect_to root_path
    end
    session.delete :order_id
    @current_order = nil
  end

  private
  def order_params
    params.require(:order).permit :status
  end

  def find_order
    @order = Order.find_by id: params[:id]
    if @order.nil?
      flash[:danger] = t "flash.order_nil"
      redirect_to admin_orders_path
    end
  end

  def correct_user
    order = Order.find_by id: params[:id]
    if order.nil?
      flash[:danger] = t "flash.order_nil"
      redirect_to root_path
    end
    unless order.user_id == current_user.id
      flash[:danger] = t "user.not_owner"
      redirect_to root_url
    end
  end
end

app/views/admin/orders/_order.html.erb
<tr>
  <td class="td-btn">
    <%= link_to user_avatar_select(order.user), user_path(order.user) %>
  </td>
  <td><%= link_to order.user.name, user_path(order.user) %></td>
  <td><%= link_to order.id, admin_order_path(order) %></td>
  <td><%= number_to_currency order.total_pay%></td>
  <td><%= order.status%></td>
  <td>
    <%= link_to t("edit.title"), edit_admin_order_path(order)%>
  </td>
</tr>

app/views/admin/orders/edit.html.erb
<% provide :title, t("edit.title") %>
<h1><%= t "edit.order_description" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @order] do |f| %>

      <%= f.label :status %>
      <%= f.select :status, options_for_select(@statuses.collect{
        |key, value|[key, key]}, @order.status) %>

      <%= f.submit t("edit.button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% provide :title, t("order.order") %>
<div class="td-admin-order-index">
  <%= render "shared/admin_filter_order_form" %>
  <table class="col-md-8 col-md-offset-2 td-admin-order">
    <tr>
      <th></th>
      <th><%= t "user.name" %></th>
      <th><%= t "order.id" %></th>
      <th><%= t "order.total" %></th>
      <th><%= t "order.status" %></th>
      <th></th>
      <th></th>
    </tr>
    <%= render @orders %>
  </table>
  <div class="td-paginate"><%= will_paginate %></div>
  <div class="clearfix"></div>
</div>
<div class="clearfix"></div>

app/views/admin/orders/show.html.erb
<% provide :title, t("order.order") %>
<%= t "order.order" %>: <%= @order.id %>
<%= link_to t("edit.title"), edit_admin_order_path(@order) %>
<table>
  <tr>
    <th><%= t "order.name" %></th>
    <th><%= t "order.quanity" %></th>
    <th><%= t "order.unit_price" %></th>
    <th></th>
  </tr>
  <%= render @order_details %>
</table>
<%= t "order.total" %>: <%= number_to_currency @order.total_pay %>
<div class="clearfix"></div>