config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "help" => "static_pages#help"
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  get "suggestion" => "suggestions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :products, only: [:show, :index] do
    resources :comments, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :update, :index]
  resources :order_details, except: [:show, :new]
  resources :comments
  resources :categories, only: [:show, :index]
  resources :users, except: [:destroy]
  namespace :admin do
    resources :users, only: [:destroy, :index]
    resources :categories
    resources :products
    resources :suggestions, only: [:index, :destroy]
    resources :orders, except: [:new, :destroy, :create]
  end
  resources :relationships, only: [:create, :destroy, :index]
  resources :rates, only: [:create]
  resources :suggestions, only: [:new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  has_attached_file :image, styles: {medium: "300x300", large: "450x450#"}
  has_many :comments, dependent: :destroy
  has_many :order_details
  has_many :rates, dependent: :destroy

  validates :category_id, presence: true
  validates :description, presence: true
  validates :name, presence: true
  validates :number, presence: true
  validates :price, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  scope :order_by_time, -> {order created_at: :desc}
  scope :order_by, -> (filter, direction) {order filter + " " + direction}
  scope :order_by_rate, -> (direction){ 
    joins(:rates)
    .group("products.id")
    .order("avg(rates.vote) #{direction}")
  }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :find_product, except: [:index, :new, :create]

  def index
    @products = if params[:order] && params[:direction]
      Product.order_by(check_column(params[:order]), check_direction(params[:direction]))
        .paginate page: params[:page], per_page: Settings.size
    elsif params[:direction]
      Product.order_by_rate(check_direction params[:direction])
        .paginate page: params[:page], per_page: Settings.size
    else
      Product.order_by_time.paginate page: params[:page], per_page: Settings.size
    end
  end

  def new
    @product = Product.new
    @categories = Category.all.order_by_name
    if @categories.empty?
      flash[:danger] = t "flash.cate_nil"
      redirect_to new_admin_category_path
    end
  end

  def show
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "productindex.success"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all.order_by_name
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "productindex.update_success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t "productindex.delete_success"
      redirect_to admin_products_path
    end
  end

  private
  def product_params
    params.require(:product).permit :name, :description, :image,
      :price, :number, :category_id
  end

  def find_product
    @product = Product.find_by_id params[:id]
    if @product.nil?
      flash[:danger] = t "flash.prod_nil"
      redirect_to products_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, :normal_user?, only: [:show, :index]
  
  def show
    session[:return_to] ||= request.referer
    @category = Category.all
    @product = Product.find_by id: params[:id]
    @rate = Rate.new
    @votes = Rate.votes
    @order_detail = current_order.order_details.new
    if @product.nil?
      flash[:danger] = t "flash.prod_nil"
      redirect_to products_path
    end
  end

  def index
    @order_detail = current_order.order_details.new
    @products = if params[:order] && params[:direction]
      order_prod Product
    elsif params[:direction]
      order_prod_rate Product
    else
      order_prod_default Product
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image_select product
    if product.image.exists?
      image_tag product.image.url(:medium),
        id: "image-preview",
        class: "img-responsive img-rounded"
    else
      image_tag "http://i.imgur.com/OnL5mP2.jpg",
        id: "image-preview",
        class: "img-responsive img-rounded"
    end
  end
end

app/views/admin/products/_product.html.erb
<div>
  <li id="product-<%= product.id %>">
    <span class="image-show">
      <%= link_to product_image_select(product),admin_product_path(product) %>
    </span><br>
    <span class="name">
      <%= t "product.name" %><%= product.name %>
    </span><br>
    <span class="description">
      <%= t "product.description" %><%= product.description %>
    </span><br>
    <span class="price">
      <%= t "product.price" %><%= number_to_currency product.price %>
    </span><br>
    <span class="number"><%= t "product.number"  %><%= product.number %></span><br>
    <% if product.rates.average(:vote).present? %>
      <span class="rate">
        <%= t "product.rate" %><%= product.rates.average :vote %>
      </span><br>
    <% end %>
    <span>
      <%= link_to t("edit.title"), 
        edit_admin_product_path(product), 
        class: "btn btn-primary" %>
    </span>
    <span>
      <%= link_to t("destroy.button"), admin_product_path(product),
        method: :delete,
        class: "btn btn-primary",
        data: {confirm: t("destroy.confirm")} %>
    </span>
  </li>
</div>
<div class="clearfix"></div>

app/views/admin/products/edit.html.erb
<% provide :title, t("edit.title") %>
<h1><%= t "edit.prod_description" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>

      <%= product_image_select @product %>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>

      <%= f.label :number %>
      <%= f.number_field :number, class: "form-control" %>

      <%= f.label :category_id %>
      <%= f.select :category_id, @categories.collect{|p| [p.name, p.id]} %>

      <%= f.submit t("edit.button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, t("productindex.title") %>
<div class="col-md-8">
  <%= render "shared/filter_form" %>
  <%= link_to t("productindex.create"), new_admin_product_path, class: "btn btn-primary" %>
  <%= will_paginate %>
  <ul class="products" id="current-product">
    <%= render @products %>
  </ul>
  <%= will_paginate %>
</div>
<div class="clearfix"></div>

app/views/admin/products/new.html.erb
<% provide :title, t("create.title_prod") %>
<h1><%= t "create.title_prod" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>

      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>

      <%= f.label :number %>
      <%= f.number_field :number, class: "form-control" %>

      <%= f.label :category_id %>
      <%= f.select :category_id, @categories.collect{|p| [p.name, p.id]} %>

      <%= f.submit t("create.button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide :title, @product.name %>
<div class="col-md-8">
  <ul>
    <%= render @product %>
   </ul>
</div>
<div class="clearfix"></div>